/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bull Board UI for queue monitoring */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bull Board UI HTML page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin dashboard */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Admin dashboard data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            stats?: {
                                /**
                                 * @description Total number of jobs
                                 * @example 1250
                                 */
                                totalJobs?: number;
                                /**
                                 * @description Number of active jobs
                                 * @example 25
                                 */
                                activeJobs?: number;
                                /**
                                 * @description Number of completed jobs
                                 * @example 1200
                                 */
                                completedJobs?: number;
                                /**
                                 * @description Number of failed jobs
                                 * @example 25
                                 */
                                failedJobs?: number;
                                /**
                                 * @description Total number of users
                                 * @example 100
                                 */
                                totalUsers?: number;
                                /**
                                 * @description Total number of webhooks
                                 * @example 50
                                 */
                                totalWebhooks?: number;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            responses: {
                /** @description User registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description User already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid credentials */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout the current user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token refreshed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description New JWT access token */
                            token?: string;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a new job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JobSubmitRequest"];
                };
            };
            responses: {
                /** @description Job submitted successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get status of a specific job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the job to get */
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job details retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Job not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all jobs for the authenticated user */
        get: {
            parameters: {
                query?: {
                    /** @description Filter jobs by status */
                    status?: "waiting" | "active" | "completed" | "failed" | "delayed";
                    /** @description Maximum number of jobs to return */
                    limit?: number;
                    /** @description Number of jobs to skip */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Jobs retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Total number of jobs matching the criteria */
                            total?: number;
                            jobs?: components["schemas"]["JobResponse"][];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all webhooks for the authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Webhooks retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookResponse"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Add a new webhook */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookCreateRequest"];
                };
            };
            responses: {
                /** @description Webhook created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a webhook */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the webhook to update */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookUpdateRequest"];
                };
            };
            responses: {
                /** @description Webhook updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Webhook not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Protected webhook notification route */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the webhook */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Webhook notification received */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Webhook not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Delete a webhook */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the webhook to delete */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Webhook deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Webhook not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example {
         *       "message": "Invalid input data",
         *       "code": "VALIDATION_ERROR"
         *     } */
        Error: {
            /** @description Error message */
            message?: string;
            /** @description Error code */
            code?: string;
        };
        SuccessResponse: {
            /**
             * @description Indicates if the operation was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Success message
             * @example Operation completed successfully
             */
            message?: string;
        };
        Job: {
            /**
             * @description Auto-generated unique identifier
             * @example job_123456
             */
            id?: string;
            /**
             * @description Job name
             * @example dataExport
             */
            name: string;
            /**
             * @description Job data payload
             * @example {
             *       "format": "csv",
             *       "filters": {
             *         "date": "2025-06-28"
             *       }
             *     }
             */
            data?: Record<string, never>;
            /**
             * @description Current job status
             * @example active
             * @enum {string}
             */
            status?: "waiting" | "active" | "completed" | "failed" | "delayed";
            /**
             * @description Job progress percentage (0-100)
             * @example 75
             */
            progress?: number;
            /**
             * @description Job execution result
             * @example {
             *       "fileUrl": "https://example.com/exports/data.csv",
             *       "recordCount": 1250
             *     }
             */
            result?: Record<string, never>;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-06-28T12:00:00Z
             */
            createdAt?: string;
        };
        JobSubmitRequest: {
            /**
             * @description Job name
             * @example dataExport
             */
            name: string;
            /**
             * @description Job data payload
             * @example {
             *       "format": "csv",
             *       "filters": {
             *         "date": "2025-06-28"
             *       }
             *     }
             */
            data?: Record<string, never>;
        };
        JobResponse: {
            /**
             * @description Auto-generated unique identifier
             * @example job_123456
             */
            id?: string;
            /**
             * @description Job name
             * @example dataExport
             */
            name?: string;
            /**
             * @description Current job status
             * @example active
             * @enum {string}
             */
            status?: "waiting" | "active" | "completed" | "failed" | "delayed";
            /**
             * @description Job progress percentage (0-100)
             * @example 75
             */
            progress?: number;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-06-28T12:00:00Z
             */
            createdAt?: string;
        };
        User: {
            /**
             * @description Auto-generated unique identifier
             * @example user_123456
             */
            id?: string;
            /**
             * @description User's username
             * @example johndoe
             */
            username: string;
            /**
             * Format: email
             * @description User's email
             * @example john.doe@example.com
             */
            email: string;
            /**
             * Format: password
             * @description User's password (hashed)
             * @example ********
             */
            password: string;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-06-28T12:00:00Z
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             * @example 2025-06-28T12:00:00Z
             */
            updatedAt?: string;
        };
        UserResponse: {
            /**
             * @description Auto-generated unique identifier
             * @example user_123456
             */
            id?: string;
            /**
             * @description User's username
             * @example johndoe
             */
            username?: string;
            /**
             * Format: email
             * @description User's email
             * @example john.doe@example.com
             */
            email?: string;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-06-28T12:00:00Z
             */
            createdAt?: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description User's email
             * @example john.doe@example.com
             */
            email: string;
            /**
             * Format: password
             * @description User's password
             * @example securePassword123
             */
            password: string;
        };
        LoginResponse: {
            /**
             * @description JWT access token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            token?: string;
            user?: components["schemas"]["UserResponse"];
        };
        Webhook: {
            /**
             * @description Auto-generated unique identifier
             * @example webhook_123456
             */
            id?: string;
            /**
             * Format: uri
             * @description Webhook URL
             * @example https://example.com/webhooks/callback
             */
            url: string;
            /**
             * @description Events to trigger this webhook
             * @example [
             *       "job.completed",
             *       "job.failed"
             *     ]
             */
            events?: string[];
            /**
             * @description Whether the webhook is active
             * @example true
             */
            active?: boolean;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-06-28T12:00:00Z
             */
            createdAt?: string;
        };
        WebhookCreateRequest: {
            /**
             * Format: uri
             * @description Webhook URL
             * @example https://example.com/webhooks/callback
             */
            url: string;
            /**
             * @description Events to trigger this webhook
             * @example [
             *       "job.completed",
             *       "job.failed"
             *     ]
             */
            events?: string[];
            /**
             * @description Whether the webhook is active
             * @default true
             * @example true
             */
            active: boolean;
        };
        WebhookUpdateRequest: {
            /**
             * Format: uri
             * @description Webhook URL
             * @example https://example.com/webhooks/callback
             */
            url?: string;
            /**
             * @description Events to trigger this webhook
             * @example [
             *       "job.completed",
             *       "job.failed"
             *     ]
             */
            events?: string[];
            /**
             * @description Whether the webhook is active
             * @example true
             */
            active?: boolean;
        };
        WebhookResponse: {
            /**
             * @description Auto-generated unique identifier
             * @example webhook_123456
             */
            id?: string;
            /**
             * Format: uri
             * @description Webhook URL
             * @example https://example.com/webhooks/callback
             */
            url?: string;
            /**
             * @description Events to trigger this webhook
             * @example [
             *       "job.completed",
             *       "job.failed"
             *     ]
             */
            events?: string[];
            /**
             * @description Whether the webhook is active
             * @example true
             */
            active?: boolean;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-06-28T12:00:00Z
             */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
